# Generated by Django 4.1.7 on 2023-03-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0002_alter_registration_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Introduction_brief',
            field=models.TextField(null=True),
        ),
    ]
