# Generated by Django 4.1.7 on 2023-03-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0003_alter_registration_introduction_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='About_website',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Average_review_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Num_of_enrolled_students',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Num_of_reviews',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Qualification',
            field=models.TextField(null=True),
        ),
    ]
