# Generated by Django 4.1.7 on 2023-04-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0004_alter_registration_about_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='paid_amount',
            field=models.FloatField(null=True),
        ),
    ]
